# Generated by Django 3.1.7 on 2021-03-24 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(db_column='PCODE', max_length=50)),
                ('pname', models.CharField(db_column='PNAME', max_length=100)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=200, null=True)),
                ('content', models.CharField(blank=True, db_column='CONTENT', max_length=1000, null=True)),
                ('is_complete', models.IntegerField(blank=True, db_column='IS_COMPLETE', null=True)),
                ('priority', models.IntegerField(blank=True, db_column='PRIORITY', null=True)),
                ('end_date', models.DateField(blank=True, db_column='END_DATE', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE', null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE', null=True)),
                ('pcode', models.ForeignKey(db_column='PCODE', on_delete=django.db.models.deletion.CASCADE, to='todoapp.projectcode')),
                ('user_id', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
